### ISSUE TITLE
[ERROR] [main.py:197] Unexpected error 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by lily5463** [Galactic647/GI-3DMigoto-Tools#2]
I got this error when I'm trying to fix hash with the Hash Fixer tool

**Comment by weebo404** [comment]
This is what my mods folder look like


![image](https://user-images.githubusercontent.com/70020377/231952732-cca2b15d-bdcf-4e9e-a085-24e300e4cd44.png)

**Comment by Galactic647** [comment]
Check the new release and see if the error still persist, if it does then check if it has a file that caused the error and send it here
